### ISSUE TITLE
slowing down + out of memory crash

### ISSUE THREAD

**Issue by peter-lyons-kehl** [garywill/LAN-port-scan-forbidder#4]
Thank you for this Gary. Good intention.

Unfortunately,
1. After installing, it slows Firefox down.
2. After enabling/checking the Notifications preference, this extension with http://samy.pl/webscan crashed my Firefox.=, with out of memory.

**Comment by garywill** [comment]
> After enabling/checking the Notifications preference, this extension with http://samy.pl/webscan crashed my Firefox.=, with out of memory.

That webscan test site continuously send lots of requests to LAN, so it will popup many many notifications to system. So, don't do that test with notification option on.

> it slows Firefox down.

There may be some optimizations that can be done. But, soso, I guess. 🤷‍♂️ I'll try when I get time

**Comment by garywill** [comment]
Should have been fixed now
